#!/usr/bin/env bash
# it shows your local ip addresses
set -e

networksetup -listallhardwareports

echo "en0: `ipconfig getifaddr en0`"
echo "en1: `ipconfig getifaddr en1`"
echo "en2: `ipconfig getifaddr en2`"
echo "en3: `ipconfig getifaddr en3`"
echo "en4: `ipconfig getifaddr en4`"
echo "en5: `ipconfig getifaddr en5`"
echo "en6: `ipconfig getifaddr en6`"
echo "en7: `ipconfig getifaddr en7`"
echo "en8: `ipconfig getifaddr en8`"
echo "en9: `ipconfig getifaddr en9`"
echo "vboxnet0: `ipconfig getifaddr vboxnet0`"
echo "vboxnet1: `ipconfig getifaddr vboxnet1`"
echo "vboxnet2: `ipconfig getifaddr vboxnet2`"
echo "vboxnet3: `ipconfig getifaddr vboxnet3`"
echo "vboxnet4: `ipconfig getifaddr vboxnet4`"
echo "vboxnet5: `ipconfig getifaddr vboxnet5`"
