#! /bin/bash
# just learning some shell thanks to ryan tomayko
# http://shellhaters.heroku.com/
# for docs see http://shellhaters.heroku.com/posix

set -e
/usr/local/bin/http http://shellhaters.heroku.com |
tr -c "a-zA-Z" "\n"           |
grep -v  '^$'                 |
sort                          |
uniq -c                       |
sort -rn                      |
head -25
